scieloorg/search-journals

- proc/updatesearch/updatesearch.py
- solr/solrconfig.xml
> Adicionado a capacidade de remover itens inexistentes na base de dados.

- iahx/locale/en/texts.ini
- iahx/locale/es/texts.ini
- iahx/locale/pt/texts.ini
- iahx/static/js/main.js
- iahx/templates/custom/history.html
- iahx/templates/custom/result-clusters.html
- iahx/templates/custom/top-searchbar.html
- Necessário realizar a atualização do iahx-core 
- Necessário limpar cache do browser antes das validações devido a alterações do JS da interface.
> Implementações referentes a iteracao 3

- iahx/static/js/main.js
- iahx/templates/custom/base.html
- iahx/templates/custom/export-ris.html
- iahx/templates/custom/index.html
- iahx/templates/custom/result-doc-actions.html
- iahx/templates/custom/result-doc.html
- iahx/templates/custom/result-navigation.html
- iahx/templates/custom/result-topbar.html
- iahx/templates/custom/top-menu-en.html
- iahx/templates/custom/top-menu-es.html
- iahx/templates/custom/top-menu-pt.html
- iahx/templates/custom/top-searchbar.html
@jamilatta 
Favor quando possivel atualizar repositório do projeto e também do iahx-core.
[]s
> Ajustes referentes a iteração 5 e 6

- iahx/static/js/vendor/excanvas.min.js
- iahx/templates/custom/base.html
- iahx/templates/custom/history.html
- iahx/templates/custom/result-doc-actions.html
- iahx/templates/custom/top-searchbar.html
- solr/schema.xml
Para este PR é necessário:
- atualizar repositório iahx-core
- atualizar repositório do projeto
- limpar cache do navegador antes de realizar as validações.
[]s
> Ajustes referentes a iteracao 6 e escopo do projeto

- iahx/locale/en/texts.ini
- iahx/locale/es/texts.ini
- iahx/locale/pt/texts.ini
- iahx/static/js/main.js
- iahx/templates/custom/history.html
- iahx/templates/custom/result-navigation.html
- iahx/templates/custom/top-searchbar.html
Por favor:
- Atualizar iahx-core
- Atualizar repositório do projeto com este PR.
Obrigado.
> Ajuste referentes a iteracao 7 e escopo do projeto

- iahx/config/config-DEV.xml
- iahx/locale/en/texts.ini
- iahx/locale/es/texts.ini
- iahx/locale/pt/texts.ini
- iahx/static/css/scielo-portal-custom.css
- iahx/static/js/main.js
- iahx/templates/custom/base.html
- iahx/templates/custom/result-clusters.html
- iahx/templates/custom/result-doc-actions.html
- iahx/templates/custom/result-doc.html
- iahx/templates/custom/result-navigation.html
- solr/solrconfig.xml
Favor realizar a atualização do ambiente de homologação.
> Ajustes referentes a iteracao 8

- proc/updatesearch/updatesearch.py
> Correção do processamento de "sanitização".

- proc/updatesearch/pipeline_xml.py
> Mantido o author com LastName, FirstName

- iahx/static/css/scielo-portal.css
> Ajuste na posição da caixa de compartilhamento

- iahx/static/css/scielo-portal-custom.css
- iahx/static/js/main.js
- iahx/templates/custom/base.html
- iahx/templates/custom/result-actions.html
- iahx/templates/custom/result-clusters.html
- iahx/templates/custom/top-searchbar.html
Para a resolução do issue #215 é necessário também a atualização do iahx-core.
> Adiciona variavel para controle da página atual

- iahx/static/js/main.js
- iahx/templates/custom/history.html
- iahx/templates/custom/top-searchbar.html
* É necessário a atualização do iahx-core
> Adiciona form completo na página de histórico. #219

- iahx/static/css/scielo-portal.min.css
- iahx/static/js/main.js
- iahx/templates/custom/index.html
- iahx/templates/custom/top-searchbar.html
O item do tooltip contextual foi adicionado na estrutura da ScIELO - ref. ao ticket #325 
Podem validar?
> tk325: Tooltip contextual de ajuda de busca no campo

- iahx/static/css/scielo-portal.min.css
- iahx/static/js/main.js
- iahx/templates/custom/result-clusters.html
Itens adicionados ref. ao ticket #328. 
O texto do botão deve ser atualizado nesta variável - {{texts.FILTER}}.
Podem validar?
> tk328: Inclusão botão limpar filtro e atualização desta opção

- iahx/static/css/scielo-portal.min.css
Correção referente a issue: Novas traduções #339
> tk334: correção botão traduções

- iahx/locale/en/texts.ini
- iahx/locale/es/texts.ini
- iahx/locale/pt/texts.ini
- iahx/static/js/main.js
- iahx/templates/custom/result-actions.html
- solr/schema.xml
Adicionalmente a aplicação deste PR é necessário os seguintes ajustes para os tickets #372, #378, #379:
- Atualizar iahx-core (git pull)
- Atualizar arquivo environment.php (search scielo) que não é link simbólico
- Atualizar arquivo environment.php (search books) que não é link simbólico
- Adicionar no arquivo config.xml os seguintes parâmetros:
```
<max_documents_per_page>100</max_documents_per_page>
<use_https>true</use_https>
```
Obrigado.
> Ajustes referentes ao milestone 19

- iahx/static/css/scielo-portal.min.css
- iahx/static/js/main.js
- iahx/templates/custom/result-doc.html
Direção do dropdown de métricas
Inserido script que verifica qual deve ser a posição do dropdown.
Incluido css para mudar a direção da seta exibida ao abrir as metricas.
fix #413
> direção do dropdown de metricas

- docker-compose-dev.yml
- iahx/config/config.xml
- iahx/locale/en/texts.ini
- iahx/locale/es/texts.ini
- iahx/locale/pt/texts.ini
Corrigi labels e link da coleção Paraquai e West Indias.
Arquivos alterados: 
docker-compose-dev.yml
iahx/config/config.xml
iahx/locale/en/texts.ini
iahx/locale/es/texts.ini
iahx/locale/pt/texts.ini
Acessando a aplicação após executar o comando: **docker-compose -f docker-compose-dev.yml up -d**
Clicando em **"mostrar todos"** no cluster de coleções:
Após filtrado acessando o texto completo dos artigos de Paraguai e West Indias:
Para realizar os teste manuais é necessário manter o filtro pela coleção Paraquai e West Indias
Não há.
https://github.com/scieloorg/search-journals/issues/444
Não há.
> Bug444 - Corrigi labels e link da coleção Paraquai e West Indias.

- docker-compose-dev.yml
- docker-compose.yml
- iahx/config/config.xml
- iahx/environment.php
- iahx/templates/custom/base.html
Inclui a linha de chamada do script de cookie Policy
Carregue o sistema, e veja se a barra com a mensagem de uso de cookies aparece.
Após, verifique os arquivos modificados.
Siga os passos anteriores.
A barra deve aparecer por padrão.
#462 
-
> incluido script de aviso de uso de cookies usando variáveis de ambiente.

- proc/updatepreprint/logging.conf
- proc/updatepreprint/pipeline_xml.py
- proc/updatepreprint/requirements.txt
- proc/updatepreprint/setup.py
- proc/updatepreprint/tests.py
- proc/updatepreprint/updatepreprint.py
> Processamento de coleta de PrePrint

- proc/updatepreprint/pipeline_xml.py
- proc/updatepreprint/requirements.txt
- proc/updatepreprint/tests.py
- proc/updatepreprint/updatepreprint.py
Cria os pipelines: coleção, tipo de documento, autores e títulos
por commits
python setup.py test
n/a
n/a
#481 
n/a
> Cria os pipelines: coleção, tipo de documento, autores e títulos

- proc/updatepreprint/pipeline_xml.py
- proc/updatepreprint/tests.py
- proc/updatepreprint/updatepreprint.py
Atualização da branch preprint para master.
> Preprint -> Master

- iahx/static/js/functions.js
Este pull request corrige a paginação da aplicação mantendo os filtros previamente aplicados pelos usuários. Rever a necessidade de submissão de formulários para paginar os resultados.
- `iahx/static/js/functions.js`: L: `3`
Para testar este pull request manualmente, deve-se:
- Iniciar uma instância da aplicação;
- Realizar a busca por algum termo;
- Aplicar os filtros sugeridos pela issue #503;
- Navegar entre as páginas;
- Observar que os filtros são mantidos e o resultado é constante.
A aplicação possui muitos formulários escondidos que servem para que os filtros sejam aplicados, eventualmente se esquecemos de aplicar algum dado/filtro nos formulários estes passam a conter menos informações do que deveriam. Pensando nisso eu resolvi modificar a lógica aplicada a função que realiza a …
> Corrige falha ao navegar entre páginas de resultados

- iahx-sites/scieloorg/templates/custom/footer.html
> Atualiza o endereço físico

- iahx/config/config.xml
- iahx/views/search.php
Adiciona uma velificação no formato JSON. É necessário que exista o IP do cliente da requisição para acessar esse endpoint.
> Adiciona uma velificação no formato JSON. É necessário que exista o IP do cliente da requisição para acessar esse endpoint.

- docker-compose.yml
- iahx-sites/scieloorg/templates/custom/result-format-summary.html
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique um contexto onde as modificações se fazem necessárias ou passe informações que contextualizam
o revisor a fim de facilitar o entendimento da funcionalidade.
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que o pull request resolve.
Indique uma issue ao qual o pull request faz relacionamento.
Indique as referências utilizadas para a elaboração do pull request.
> Inserido template tag

- solr/8.5.1/cores/solrdata/data/articles/conf/managed-schema
Adiciona os campos limpos de abstract, title, keywords
Por commits
...
.
https://github.com/scieloorg/search-journals-proc/issues/26
n/a
> Adiciona os campos limpos de abstract, title, keywords
